# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}
# sweep:
#   dir: ${paths.log_dir}/multiruns
#   subdir: ${hydra.job.num}